### ISSUE TITLE
Hi bro

### ISSUE THREAD

**Issue by mazi2021** [Toni-d-e-v/Aurora-Icloud-bypass#1]
Not working 
Error
![Uploading image.jpg…]()

**Comment by mazi2021** [comment]
error
Not working 
![Uploading 62312398-3DBF-48F2-9A8F-56B8897BBE14.jpeg…]()

**Comment by mazi2021** [comment]
![Uploading 7839CEA7-DD41-4323-8996-1A57DC23DF36.jpeg…]()

**Comment by mazi2021** [comment]
![AF8D7C3D-4248-4CA6-B0E2-7D5A31D4B65C](https://user-images.githubusercontent.com/78269019/161440673-9a3a0e34-b242-43c1-85b8-aa1c58fc0b8a.jpeg)

**Comment by Toni-d-e-v** [comment]
You did not connect your phone, please check your cable

**Comment by Toni-d-e-v** [comment]
Php script is not tested please use main automatic script

**Comment by mazi2021** [comment]
Hi bro 
Cable ok
I’m install php seever on MacOS 
No I have new error 😢 
Please help me 
Give I’m i your watsapp to help me
🙏

**Comment by Toni-d-e-v** [comment]
Php tool is not tested please download ubuntu 20.04 and boot it, and run the script. You can boot it from USB dont need to install anything. 
Good luck

**Comment by mazi2021** [comment]
Ok I’m tested 
Tanks bro

**Comment by mazi2021** [comment]
![Uploading 6902B68E-411C-4FD4-8B57-7977C57305F6.jpeg…]()

**Comment by mazi2021** [comment]
![1DA8C694-C733-40EA-B93B-BF9259AAF1B1](https://user-images.githubusercontent.com/78269019/161844287-fe4a3396-1b39-4356-8a9a-134438e271b7.jpeg)

**Comment by mazi2021** [comment]
![Uploading 73E1AC46-4C78-4C2D-B37D-F098EF00C465.jpeg…]()

**Comment by mazi2021** [comment]
Error 😭

**Comment by mazi2021** [comment]
![47F4C6DE-AE53-4CE2-A8BF-95A3878634CA](https://user-images.githubusercontent.com/78269019/161844761-af34b6f1-eace-450e-843a-7d8f65a1dee0.jpeg)

error from ubunto

**Comment by mazi2021** [comment]
I’m using ubunto 20:04
But have error
Im using 
Bypass 
After bypass Touch ID not working I can’t open menu iphone
Not working

**Comment by Toni-d-e-v** [comment]
I said php unlock was not tested, please try normal one. It will work but without calls or sms and siri and touch id

**Comment by Toni-d-e-v** [comment]
Try running with sudo

**Comment by mazi2021** [comment]
I’m try with Sudo
Not working

**Comment by mazi2021** [comment]
> 

Not working

**Comment by mazi2021** [comment]
sudo ./start.sh

**Comment by Toni-d-e-v** [comment]
Hmm share all screenshots with script automatic, that script should work for iphone 5s to iphone x under ios 15.3.1

**Comment by mazi2021** [comment]
![EFE4D1FB-AF6B-4AB8-A3DB-C35D12E37CCE](https://user-images.githubusercontent.com/78269019/162061660-a66fd50f-2308-45e4-b64d-a0444f284ef0.jpeg)

Not working my iPhone home pad is lock

**Comment by mazi2021** [comment]
![image](https://user-images.githubusercontent.com/78269019/162062097-4dbe98c6-2065-49ef-abef-96da9099947d.jpg)
Please wait 3utoo

**Comment by mazi2021** [comment]
![image](https://user-images.githubusercontent.com/78269019/162062316-ac148ab3-fcf3-4d8b-b108-f49e29b3b7f0.jpg)
After bypass

**Comment by Leonsanchez988** [comment]
Did it work for you??
