### ISSUE TITLE
iphone 7

### ISSUE THREAD

**Issue by realartin** [Toni-d-e-v/Aurora-Icloud-bypass#13]
hi sir
does this tool works on iphone 7 ios 15.7.8 ?
my phone is on hello screen and i need to bypass it with sim working
tnx a lot

**Comment by MallinathR** [comment]
@realartin bro is it work???

**Comment by Khanafsar55991** [comment]
> @realartin bro is it work???

Carry on

**Comment by MallinathR** [comment]
Bro it is not detecting the device...

**Comment by Toni-d-e-v** [comment]
Check the cable.

Jailbreak first.

Run the script.

**Comment by MallinathR** [comment]
I am doing in WSL and I think WSL doesn't natively support USB.

**Comment by Leonsanchez988** [comment]
sudo apt install usbmuxd 


Enter this code, it is so that Ubuntu or WSL can detect the USB port, do not try it yet, I am still in the process of doing the bypass. You can help with chatgpt

**Comment by Leonsanchez988** [comment]
Please let me know if it works for you :D

**Comment by MallinathR** [comment]
whenever I connect iPhone via usb it suddenly start connecting and disconnecting. I don't know why it is happening :(

**Comment by Toni-d-e-v** [comment]
Maybe WSL error, this tool to be honest is OLD, but it has worked on my iphone 5s its untethered jailbreak
