### ISSUE TITLE
After run scripts 

### ISSUE THREAD

**Issue by mazi2021** [Toni-d-e-v/Aurora-Icloud-bypass#2]
![2FBBB719-DAD9-4EDA-9731-160B98149EDE](https://user-images.githubusercontent.com/78269019/162068808-13bbddcb-a6fc-4876-bde9-5295fc134163.jpeg)

not working ios12.5.5
iphone 6
Bro your close issue??
What?
I have problem 
you said send screenshots 
I’m uploaded

**Comment by mazi2021** [comment]
![Uploading 14E95E4D-9EE8-4DB6-BE26-94EEADCB6F49.jpeg…]()

**Comment by Toni-d-e-v** [comment]
@mazi2021  Script works, please check if you jailbroken the device.
If on script jailbreak does not work please go to https://checkra.in/ and jailbreak it and run the script again

**Comment by mazi2021** [comment]
bro my device already jalbracked
not works tanks
