### ISSUE TITLE
sudo: ./exe/jk: command not found

### ISSUE THREAD

**Issue by anixable** [Toni-d-e-v/Aurora-Icloud-bypass#7]
sudo: ./exe/jk: command not found

**Comment by anixable** [comment]
the jk file is missing ....

**Comment by Toni-d-e-v** [comment]
try: chmod +x ./exe/jk

**Comment by anixable** [comment]
also , i found a way to run it , the ios 16.5 not supported. i receive the error code -31

**Comment by Toni-d-e-v** [comment]
Thats jailbreak issue
